"""remove_prod_precio_lista

Revision ID: 01f530a903e7
Revises: 1f74bbf4de0c
Create Date: 2026-02-04 14:20:03.677293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01f530a903e7'
down_revision: Union[str, Sequence[str], None] = '1f74bbf4de0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'prod_precio_lista')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('prod_precio_lista', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
