"""add_invoicing_tables

Revision ID: 3c55d2b55dfd
Revises: 01f530a903e7
Create Date: 2026-02-04 15:47:16.261179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c55d2b55dfd'
down_revision: Union[str, Sequence[str], None] = '01f530a903e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # Cleanup: Only applying changes for new Invoicing tables
    
    # Establecimientos
    op.alter_column('establecimientos', 'estab_fecha_alta',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('establecimientos', 'estab_fecha_mod',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # Facturas
    op.alter_column('facturas', 'factura_numero',
               existing_type=sa.CHAR(length=7),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.alter_column('facturas', 'timbrado_numero',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('facturas', 'pago_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('facturas', 'factura_fecha_alta',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('facturas', 'factura_fecha_mod',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
               
    # Constraints & FKs for Facturas
    op.drop_index(op.f('facturas_factura_fecha_emision_idx'), table_name='facturas')
    # Use generic names or check if these constraints actually exist with these names in DB
    # The autogen detected them, so they likely exist.
    op.drop_constraint('facturas_estab_codigo_punto_codigo_fkey', 'facturas', type_='foreignkey')
    op.drop_constraint('facturas_timbrado_numero_fkey', 'facturas', type_='foreignkey')
    op.drop_constraint('facturas_pago_id_fkey', 'facturas', type_='foreignkey')
    
    op.create_foreign_key(None, 'facturas', 'pagos', ['pago_id'], ['pago_id'])
    op.create_foreign_key(None, 'facturas', 'timbrados', ['timbrado_numero'], ['timbrado_numero'])
    # Note: Composite FK for punto_expedicion might be tricky or implicit

    # Facturas Det
    op.alter_column('facturas_det', 'factura_numero',
               existing_type=sa.CHAR(length=7),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.alter_column('facturas_det', 'facdet_fecha_alta',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('facturas_det', 'facdet_fecha_mod',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('facturas_det_estab_codigo_punto_codigo_factura_numero_fkey', 'facturas_det', type_='foreignkey')

    # Puntos Expedicion
    op.alter_column('puntos_expedicion', 'punto_fecha_alta',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('puntos_expedicion', 'punto_fecha_mod',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('puntos_expedicion_estab_codigo_fkey', 'puntos_expedicion', type_='foreignkey')
    op.create_foreign_key(None, 'puntos_expedicion', 'establecimientos', ['estab_codigo'], ['estab_codigo'])

    # Tickets
    op.alter_column('tickets', 'ticket_fecha_emision',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tickets', 'fecha_alta',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tickets', 'fecha_mod',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
               
    op.drop_index('tickets_pago_id_key', table_name='tickets')
    op.create_unique_constraint(None, 'tickets', ['pago_id'])
    op.drop_constraint('tickets_pago_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'pagos', ['pago_id'], ['pago_id'])

    # Tickets Det
    op.drop_constraint('tickets_det_ticket_numero_fkey', 'tickets_det', type_='foreignkey')
    op.create_foreign_key(None, 'tickets_det', 'tickets', ['ticket_numero'], ['ticket_numero'])

    # Timbrados
    op.alter_column('timbrados', 'timbrado_numero',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('timbrados', 'timbrado_nro_desde',
               existing_type=sa.CHAR(length=7),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.alter_column('timbrados', 'timbrado_nro_hasta',
               existing_type=sa.CHAR(length=7),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.alter_column('timbrados', 'timbrado_nro_actual',
               existing_type=sa.CHAR(length=7),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.alter_column('timbrados', 'timbrado_fecha_alta',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('timbrados', 'timbrado_fecha_mod',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'venta_sucursal',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('ventas', 'venta_clientedoc',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('timbrados', 'timbrado_fecha_mod',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('timbrados', 'timbrado_fecha_alta',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('timbrados', 'timbrado_nro_actual',
               existing_type=sa.String(length=7),
               type_=sa.CHAR(length=7),
               existing_nullable=False)
    op.alter_column('timbrados', 'timbrado_nro_hasta',
               existing_type=sa.String(length=7),
               type_=sa.CHAR(length=7),
               existing_nullable=False)
    op.alter_column('timbrados', 'timbrado_nro_desde',
               existing_type=sa.String(length=7),
               type_=sa.CHAR(length=7),
               existing_nullable=False)
    op.alter_column('timbrados', 'timbrado_numero',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'tickets_det', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_det_ticket_numero_fkey'), 'tickets_det', 'tickets', ['ticket_numero'], ['ticket_numero'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_pago_id_fkey'), 'tickets', 'pagos', ['pago_id'], ['pago_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(None, 'tickets', type_='unique')
    op.create_index(op.f('tickets_pago_id_key'), 'tickets', ['pago_id'], unique=True)
    op.alter_column('tickets', 'fecha_mod',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('tickets', 'fecha_alta',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tickets', 'ticket_fecha_emision',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'puntos_expedicion', type_='foreignkey')
    op.create_foreign_key(op.f('puntos_expedicion_estab_codigo_fkey'), 'puntos_expedicion', 'establecimientos', ['estab_codigo'], ['estab_codigo'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('puntos_expedicion', 'punto_fecha_mod',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('puntos_expedicion', 'punto_fecha_alta',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('productos', 'prod_imagen_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('perfiles', sa.Column('perfil_usuario_mod', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('perfiles', sa.Column('perfil_usuario_alta', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('perfiles', sa.Column('perfil_fecha_mod', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True))
    op.add_column('perfiles', sa.Column('perfil_fecha_alta', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'perfiles', type_='foreignkey')
    op.create_foreign_key(op.f('perfiles_menu_cod_fkey'), 'perfiles', 'menu', ['menu_cod'], ['menu_cod'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_perfiles_perfil_cod'), table_name='perfiles')
    op.drop_constraint(None, 'pagos', type_='foreignkey')
    op.alter_column('pagos', 'pago_clientedoc',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.add_column('menu_det', sa.Column('menu_det_fecha_alta', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('menu_det', sa.Column('menu_det_usuario_alta', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('menu_det', sa.Column('menu_det_fecha_mod', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True))
    op.add_column('menu_det', sa.Column('menu_det_usuario_mod', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menu_det', type_='foreignkey')
    op.create_foreign_key(op.f('menu_det_cod_menu_fkey'), 'menu_det', 'menu', ['menu_cod'], ['menu_cod'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('menu_det', 'menu_det_estado',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'A'::text"))
    op.add_column('menu', sa.Column('menu_usuario_alta', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('menu_usuario_mod', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('menu_fecha_alta', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('menu_fecha_mod', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_menu_menu_cod'), table_name='menu')
    op.create_foreign_key(op.f('facturas_det_estab_codigo_punto_codigo_factura_numero_fkey'), 'facturas_det', 'facturas', ['estab_codigo', 'punto_codigo', 'factura_numero'], ['estab_codigo', 'punto_codigo', 'factura_numero'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('facturas_det', 'facdet_fecha_mod',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('facturas_det', 'facdet_fecha_alta',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('facturas_det', 'factura_numero',
               existing_type=sa.String(length=7),
               type_=sa.CHAR(length=7),
               existing_nullable=False)
    op.drop_constraint(None, 'facturas', type_='foreignkey')
    op.drop_constraint(None, 'facturas', type_='foreignkey')
    op.create_foreign_key(op.f('facturas_pago_id_fkey'), 'facturas', 'pagos', ['pago_id'], ['pago_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('facturas_timbrado_numero_fkey'), 'facturas', 'timbrados', ['timbrado_numero'], ['timbrado_numero'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('facturas_estab_codigo_punto_codigo_fkey'), 'facturas', 'puntos_expedicion', ['estab_codigo', 'punto_codigo'], ['estab_codigo', 'punto_codigo'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_index(op.f('facturas_factura_fecha_emision_idx'), 'facturas', ['factura_fecha_emision'], unique=False)
    op.alter_column('facturas', 'factura_fecha_mod',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('facturas', 'factura_fecha_alta',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('facturas', 'pago_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('facturas', 'timbrado_numero',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('facturas', 'factura_numero',
               existing_type=sa.String(length=7),
               type_=sa.CHAR(length=7),
               existing_nullable=False)
    op.alter_column('establecimientos', 'estab_fecha_mod',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('establecimientos', 'estab_fecha_alta',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_clientes_cli_documento'), table_name='clientes')
    op.create_unique_constraint(op.f('clientes_cli_documento_key'), 'clientes', ['cli_documento'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'caja_sesiones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sesiones_cajas_composite'), 'caja_sesiones', 'cajas', ['sesion_sucursal', 'sesion_cajaid'], ['caja_sucursal', 'caja_cod'])
    op.drop_index(op.f('ix_caja_sesiones_sesion_id'), table_name='caja_sesiones')
    op.create_table('empresa',
    sa.Column('empresa_cod', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empresa_nom', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('empresa_ruc', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('empresa_estado', sa.CHAR(length=1), server_default=sa.text("'A'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('empresa_usuario_alta', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('empresa_fecha_alta', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('empresa_usuario_mod', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('empresa_fecha_mod', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('empresa_cod', name=op.f('empresa_pkey'))
    )
    # ### end Alembic commands ###
