"""Initial_migration

Revision ID: e1b51e7624c4
Revises: 
Create Date: 2026-02-04 08:48:00.374632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1b51e7624c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa')
    op.create_index(op.f('ix_caja_sesiones_sesion_id'), 'caja_sesiones', ['sesion_id'], unique=False)
    op.drop_constraint(op.f('fk_sesiones_cajas_composite'), 'caja_sesiones', type_='foreignkey')
    op.create_foreign_key(None, 'caja_sesiones', 'usuarios', ['sesion_usuario_email'], ['usuario_email'])
    op.drop_constraint(op.f('clientes_cli_documento_key'), 'clientes', type_='unique')
    op.create_index(op.f('ix_clientes_cli_documento'), 'clientes', ['cli_documento'], unique=False)
    op.create_index(op.f('ix_menu_menu_cod'), 'menu', ['menu_cod'], unique=False)
    op.drop_column('menu', 'menu_fecha_alta')
    op.drop_column('menu', 'menu_fecha_mod')
    op.drop_column('menu', 'menu_usuario_mod')
    op.drop_column('menu', 'menu_usuario_alta')
    op.alter_column('menu_det', 'menu_det_estado',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'A'::text"))
    op.drop_constraint(op.f('menu_det_cod_menu_fkey'), 'menu_det', type_='foreignkey')
    op.create_foreign_key(None, 'menu_det', 'menu', ['menu_cod'], ['menu_cod'])
    op.drop_column('menu_det', 'menu_det_usuario_mod')
    op.drop_column('menu_det', 'menu_det_fecha_alta')
    op.drop_column('menu_det', 'menu_det_usuario_alta')
    op.drop_column('menu_det', 'menu_det_fecha_mod')
    op.alter_column('pagos', 'pago_clientedoc',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_foreign_key(None, 'pagos', 'caja_sesiones', ['pago_sesionid'], ['sesion_id'])
    op.create_index(op.f('ix_perfiles_perfil_cod'), 'perfiles', ['perfil_cod'], unique=False)
    op.drop_constraint(op.f('perfiles_menu_cod_fkey'), 'perfiles', type_='foreignkey')
    op.create_foreign_key(None, 'perfiles', 'menu', ['menu_cod'], ['menu_cod'])
    op.drop_column('perfiles', 'perfil_fecha_mod')
    op.drop_column('perfiles', 'perfil_usuario_mod')
    op.drop_column('perfiles', 'perfil_fecha_alta')
    op.drop_column('perfiles', 'perfil_usuario_alta')
    op.alter_column('productos', 'prod_imagen_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ventas', 'venta_clientedoc',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('ventas', 'venta_sucursal',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'venta_sucursal',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('ventas', 'venta_clientedoc',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('productos', 'prod_imagen_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('perfiles', sa.Column('perfil_usuario_alta', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('perfiles', sa.Column('perfil_fecha_alta', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('perfiles', sa.Column('perfil_usuario_mod', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('perfiles', sa.Column('perfil_fecha_mod', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'perfiles', type_='foreignkey')
    op.create_foreign_key(op.f('perfiles_menu_cod_fkey'), 'perfiles', 'menu', ['menu_cod'], ['menu_cod'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_perfiles_perfil_cod'), table_name='perfiles')
    op.drop_constraint(None, 'pagos', type_='foreignkey')
    op.alter_column('pagos', 'pago_clientedoc',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.add_column('menu_det', sa.Column('menu_det_fecha_mod', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True))
    op.add_column('menu_det', sa.Column('menu_det_usuario_alta', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('menu_det', sa.Column('menu_det_fecha_alta', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('menu_det', sa.Column('menu_det_usuario_mod', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menu_det', type_='foreignkey')
    op.create_foreign_key(op.f('menu_det_cod_menu_fkey'), 'menu_det', 'menu', ['menu_cod'], ['menu_cod'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('menu_det', 'menu_det_estado',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'A'::text"))
    op.add_column('menu', sa.Column('menu_usuario_alta', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('menu_usuario_mod', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('menu_fecha_mod', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('menu_fecha_alta', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_menu_menu_cod'), table_name='menu')
    op.drop_index(op.f('ix_clientes_cli_documento'), table_name='clientes')
    op.create_unique_constraint(op.f('clientes_cli_documento_key'), 'clientes', ['cli_documento'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'caja_sesiones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sesiones_cajas_composite'), 'caja_sesiones', 'cajas', ['sesion_sucursal', 'sesion_cajaid'], ['caja_sucursal', 'caja_cod'])
    op.drop_index(op.f('ix_caja_sesiones_sesion_id'), table_name='caja_sesiones')
    op.create_table('empresa',
    sa.Column('empresa_cod', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empresa_nom', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('empresa_ruc', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('empresa_estado', sa.CHAR(length=1), server_default=sa.text("'A'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('empresa_usuario_alta', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('empresa_fecha_alta', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('empresa_usuario_mod', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('empresa_fecha_mod', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('empresa_cod', name=op.f('empresa_pkey'))
    )
    # ### end Alembic commands ###
